### ISSUE TITLE
Dead code in DRM SETUP block

### ISSUE THREAD

**Issue by widgetii** [gehee/FPVue_RK3566#3]
As I understand this code actually does nothing https://github.com/gehee/FPVue_rk/blob/main/main.c#L526

1) `output_list` is a malloc-ed structure
2) `output_list->video_request` is set using return value in drmModeAtomicAlloc()
3) but then in `modeset_prepare` every byte in structure is overwritten by `*output_list = *out;` https://github.com/gehee/FPVue_rk/blob/main/drm.c#L522

**Comment by gehee** [comment]
This has been cleaned up.
